### ISSUE TITLE
generate / update thumbnails in the background

### ISSUE THREAD

**Issue by specterpete** [midstar/mediaweb#11]
I suggest the feature that thumbnails are generated in the background automatically as soon as new files are added or updated as soon as files have been changed or deleted,

Nice web gallery, works like a charm.

**Comment by midstar** [comment]
I have been thinking about this before and would like to have this feature myself. There are some libraries that can do this in a platform-independent way. I will investigate this more.

**Comment by specterpete** [comment]
That's good news, thanks for looking into it.

**Comment by midstar** [comment]
I have now generated a new release which includes automatic updates when files are added to the media directory. 

https://github.com/midstar/mediaweb/releases/tag/mediaweb-v1.0.0.132

It has been unit tested and partly manually tested. There might be bugs that I have not detected yet.
