### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mash55** [midstar/mediaweb#16]
Would it be possible to add functionality to browse to the last/next picture ?
Thanks

**Comment by midstar** [comment]
Absolutely. Any ideas how the UI should be uppdated? The mobile UI is very minimalistic and focused on swipe/pitch interactions and I'm not shure if additional buttons would be practical.
BR,
Joel

**Comment by mash55** [comment]
I like the minimalistic approach. It works very well on a mobile. Swiping back and forth is fast and easy. However, on a computer I am struggeling to 'swipe'... and think a centered arrow on the left and right side of the picture would make it easier to 'scroll' through the images. Thnaks for your consideration and for providing this useful tool.

**Comment by midstar** [comment]
I could add buttons that a visible on a non-mobile platform for prev/next and first/last image. To simplify you navigation you can also use the arrow keys on the keyboard (that works in the version you have today).

**Comment by mash55** [comment]
I think that would be an improvement... using the arrow keys works for me though... was unaware of this functionality.

**Comment by midstar** [comment]
Hi,

I have now supported navigation to the first image using keyboard Page Up and last image using Page Down. Also, information about the arrow keýs are now available in the README.

The release is named v1.0.1.144.

Best Regards,
Joel
