### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by fernandopal** [midstar/mediaweb#20]
can be nice to have an option to change the pictures of the folders, like having a thumbnail for each folder if you enable it on the config or something

**Comment by midstar** [comment]
Hi,

I don't really understand your request. How would you like the folder icons to be changed? Would you like the folder icon to illustrate a subset of the images inside the folder, like done in for example "Windows File Explorer" (when using the medium, large or extra large icon setting).

/Joel

**Comment by midstar** [comment]
Closing since no feedback from reporter.
