### ISSUE TITLE
Installation on raspberry pi 3 fails

### ISSUE THREAD

**Issue by specterpete** [midstar/mediaweb#29]
Hi,

I followed your install instructions, but unfortunately, the installation fails on my raspberry pi 3.
Heres the error message:

`$ sudo dpkg -i mediaweb_linux_arm.deb
dpkg: error processing archive mediaweb_linux_arm.deb (--install):
 package architecture (arm64) does not match system (armhf)
Errors were encountered while processing:
 mediaweb_linux_arm.deb
`

Best regards,
Pete

**Comment by midstar** [comment]
My misstake. I will fix the installer.

I think you could use the released zip file instead of the .deb installer. It should work also on armhf architectures.

**Comment by midstar** [comment]
The Debian installer for ARM 32 bit has now been fixed. Please let me know if it don't work.
