### ISSUE TITLE
Feature request: Delete thumbsnails / resized images

### ISSUE THREAD

**Issue by specterpete** [midstar/mediaweb#31]
It would be nice if a photo is deleted, that the corresponging images (thumbnails / resized images) in the thumbnail cache folder are also deleted. Maybe this can be added to the watcher? I saw it was already foreseen in the unit test.

**Comment by midstar** [comment]
Sure. I will have a look at this.

**Comment by specterpete** [comment]
Thanks a lot. Mediaweb is really an excellent application, thanks for sharing it with us.

Regards,
Pete

**Comment by midstar** [comment]
Finally, mediaweb has support for deleting files in the cache folder which don't have any corresponding mediafile. Checkout mediaweb 1.3.0.252.
