### ISSUE TITLE
Set interface in configuration

### ISSUE THREAD

**Issue by Aestu** [midstar/mediaweb#33]
Thank you for this project. This is simple and easy to use, just what I was looking for for my raspberry.

It would be very useful (and secure) being able to specify the interface/s where mediaweb will listen. Something like:

interface = 192.168.1.141

This is a very common feature in configuration of servers.

Thanks again,

Alfredo

**Comment by midstar** [comment]
Thanks for using MediaWeb and your request. I will fix a new parameter for listening interface in next release.

**Comment by midstar** [comment]
Added ip parameter in mediaweb-v1.1.0.238. Let me know if this works or not for you.

**Comment by Aestu** [comment]
It works. Thank you Joel!
