### ISSUE TITLE
mediaweb creates more and more thumbnails of themselfves 

### ISSUE THREAD

**Issue by Aestu** [midstar/mediaweb#34]
I think I found a minor bug. I enabled preview so I saved this mediaweb.conf file:

```
port = 80
mediapath = /mnt/too/copias-seguridad/intercambio-pendrive-sandisk/AXEL/FOTOS-AXEL
cachepath = /mnt/too/copias-seguridad/intercambio-pendrive-sandisk/AXEL/FOTOS-AXEL
enablepreview = on
previewmaxside = 1280
```
Please pay attention to the paths (my mistake). They are the same. More and more thumbnails are generated for the same file (names start with one or more underscores). Everything works fine if I comment out or remove the cachepath line of config file.

Thanks,

Alfredo

**Comment by midstar** [comment]
Thank you for your feedback. MediaWEB will no longer allow the same path in mediapath and cachepath since version mediaweb-v1.1.0.238.

**Comment by Aestu** [comment]
It works. The server doesn't start if both params have the same value. Thank Joel!
