### ISSUE TITLE
Can't access to external ( 4G for example )

### ISSUE THREAD

**Issue by billouetaudrey** [midstar/mediaweb#36]
Hi,

Anyone can help me to give access to external internet ? 

Apache OK
Other server like Plex, Domoticz Ok

But Mediaweb not ok 

Work in local 👍 

Thanks

**Comment by midstar** [comment]
Hi,

MediaWeb will not differ from any other server software (such as Apache) in how the traffic is routed. It's plain HTTP and if you have enabled encryption its HTTPS.

Which port are you using? Have you enabled HTTPS?

**Comment by billouetaudrey** [comment]
Hi,

I use stock port, like 9834

I don't enable https, because I don't really know how, I need to search more... I enable login/password with Mediaweb and with .htaccess ;)

**Comment by billouetaudrey** [comment]
BTW , very nice work !

**Comment by midstar** [comment]
Some additional questions:

- Do you have a static external IP or are you using a dynamic DNS?
- Have you configured your router to rout external traffic to the MediaWeb server on port 9834?

**Comment by billouetaudrey** [comment]
I have DynDns ;)
I don't open yet the port but in local, I can't access too, only local ip + port work

**Comment by midstar** [comment]
I dont understand your last message. If you only have problems while accessing MediaWeb from Internet and you dont have any problems with Appache I bet you have some errors in your router  WAN port forwarding configuration.

**Comment by billouetaudrey** [comment]
Me noob and I'm sorry 
I though if I use mediaweb with my local computer (so same wifi as server ) , i don't need to open port
But after open port, now it's working fine
Thanks again
