### ISSUE TITLE
Feature Request : Add multiple folder to mediaweb

### ISSUE THREAD

**Issue by billouetaudrey** [midstar/mediaweb#37]
Hi,

I have pic in /mnt/Elements/Documents/Picture
and in 
/home/pi/Cloud

Is it possible to add these folder to mediaweb.conf ?

Thanks :D

**Comment by billouetaudrey** [comment]
Maybe I found a solution, ln -s /home/pi/Cloud /mnt/Elements/Documents/Picture

I don't see the folder on mediaweb, but work if I do http://xxx:9834/?path=Cloud

**Comment by midstar** [comment]
Hi. It was a good idea to use symbolic links. I have added full support of symbolic links including thumbnail generation for files within the symbolic directory.

Try out release mediaweb-v1.2.0.241

**Comment by billouetaudrey** [comment]
Hi

Sorry for delay, just update :) Work like a charm :) thanks very much :D
